# Generated by Django 4.1.5 on 2023-09-20 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipe_slug'),
        ('recipes', '0004_alter_recipe_updated_at'),
    ]

    operations = [
    ]
